Address issue with isdir (searches path) vs isfolder
pace-neutrons/Herbert pull request #285
Opened 2021-02-02 16:00 UTC by oerc0122

#284 is happening because `isdir` searches the MATLAB path as well as the current working directory.

2021-02-02 16:03 UTC, hsautessella approved these changes
Fixes the issue 👍

2021-02-02 16:08 UTC, nickbattam-tessella reviewed
Are there any other instances of using `isdir` in the code? over `isfolder`

`isfolder` was introduced in R2017b - if we need to maintain support for older MATLAB we will need to add an alias to `isdir` on those

2021-02-02 16:12 UTC, oerc0122 commented
> Are there any other instances of using `isdir` in the code? over `isfolder`
> 
> `isfolder` was introduced in R2017b - if we need to maintain support for older MATLAB we will need to add an alias to `isdir` on those

Most seem to be a `.isdir` call, which I suspect is different. 
```
Horace/admin/pCode_Horace_kit.m:directories = find([contents.isdir]);
Herbert/herbert_core/admin/clean_temporary_directory.m:        if ~files(j).isdir
Herbert/herbert_core/admin/copy_files_list.m:isdir = logical(cat(1,localFiles_list.isdir));
Herbert/herbert_core/admin/copy_files_list.m:isfile = ~isdir;
Herbert/herbert_core/admin/copy_files_list.m:dirs = localFiles_list(isdir); % select only directory entries from the current listing
Herbert/herbert_core/admin/copy_files_list.m:isfile = ~logical(cat(1,filelist.isdir));
Herbert/herbert_core/admin/genpath_special.m:isdir = logical(cat(1,files.isdir));
Herbert/herbert_core/admin/genpath_special.m:dirs = files(isdir); % select only directory entries from the current listing
Herbert/herbert_core/classes/MPIFramework/@ClusterMPI/private/find_and_return_host_files_.m:    if the_file.isdir
Herbert/herbert_core/classes/MPIFramework/@MessagesFilebased/private/parse_folder_contents_.m:if file_struc.isdir
Herbert/herbert_core/classes/MPIFramework/@MessagesParpool/private/parce_folder_contents_.m:is_mess = arrayfun(@(x)(~x.isdir && strncmpi(mess_template,x.name,len)),folder_contents);
Herbert/herbert_core/utilities/files/dir_name_list.m:    list=contents_to_namecellstr(contents,find([contents.isdir]));
Herbert/herbert_core/utilities/files/dir_name_list.m:    list_all=contents_to_namecellstr(contents,find([contents.isdir]));
Herbert/herbert_core/utilities/files/dir_name_list.m:                list=[list,contents_to_namecellstr(contents,find([contents.isdir]))];
Herbert/herbert_core/utilities/files/dir_name_list.m:        list=contents_to_namecellstr(contents,find([contents.isdir]));
Herbert/herbert_core/utilities/files/dir_name_list.m:                excllist=[excllist,contents_to_namecellstr(contents,find([contents.isdir]))];
Herbert/herbert_core/utilities/files/file_name_list.m:    list=contents_to_namecellstr(contents,find(~[contents.isdir]));
Herbert/herbert_core/utilities/files/file_name_list.m:    list_all=contents_to_namecellstr(contents,find(~[contents.isdir]));
Herbert/herbert_core/utilities/files/file_name_list.m:                list=[list,contents_to_namecellstr(contents,find(~[contents.isdir]))];
Herbert/herbert_core/utilities/files/file_name_list.m:        list=contents_to_namecellstr(contents,find(~[contents.isdir]));
Herbert/herbert_core/utilities/files/file_name_list.m:                excllist=[excllist,contents_to_namecellstr(contents,find(~[contents.isdir]))];
Herbert/herbert_core/utilities/files/sync_folders.m:    if ~isdir(p1), mkdir(p1); end
Herbert/herbert_core/utilities/files/sync_folders.m:    if ~isdir(p2), mkdir(p2); end
Herbert/herbert_core/utilities/files/sync_folders.m:        if files1(nf1).isdir
Herbert/herbert_core/utilities/files/sync_folders.m:        if files1(nf1).isdir % is a dir
Herbert/herbert_core/utilities/files/sync_folders.m:        if files2(nf2).isdir % is a dir
Herbert/herbert_core/utilities/files/update_svn_revision_info.m:    if files_list(i).isdir
Herbert/herbert_core/utilities/general/dir2path.m:    dirs=files(cat(1,files.isdir));
Herbert/herbert_core/utilities/general/dir2path.m:    ok=cat(1,files.isdir);
Herbert/herbert_core/utilities/general/dir2path.m:            if isempty(ext)     % could be a shortcut (isdir doesn't indicate correctly)
Horace/admin/pCode_Horace_kit.m:directories = find([contents.isdir]);
matlab-xunit/src/TestSuite.m:            if isdir(name)
matlab-xunit/src/TestSuite.m:                        if isdir(relativePath)
```

2021-02-02 16:21 UTC, nickbattam-tessella commented
Confirm that the `.isdir` calls are referring to a file struct

2021-02-02 16:33 UTC, hsautessella commented
If we need a pre 2017b compatible check, there's `exist(fullfile(pwd(), 'dir_name'), 'dir')`

2021-02-03 16:00 UTC, nickbattam-tessella requested changes
Update use of `isdir()` in `herbert_core/utilities/files/sync_folders.m`

2021-02-04 10:15 UTC, nickbattam-tessella approved these changes
Issue #286 will replace the `exist( ) == 7` syntax

2021-02-04 11:47 UTC, hsautessella requested changes

2021-02-04 11:47 UTC, hsautessella commented on _test/shared/matlab_xunit/xunit/TestSuite.m
> +            if exist(name, 'dir') == 7
We don't need the `==7` here. The `if` statement will implicitly cast to a logical

2021-02-04 13:26 UTC, hsautessella approved these changes

2021-02-04 16:37 UTC, merged