Fix outputs in simulate
pace-neutrons/Herbert pull request #357
Opened 2021-05-07 11:14 UTC by oerc0122

Fix `simulate`'s error handling (seems to be untested in Herbert?)

2021-05-07 11:20 UTC, cmarooney-stfc requested changes

2021-05-07 11:20 UTC, cmarooney-stfc commented on herbert_core/applications/multifit/@mfclass/simulate.m
> +[wmask, msk_out] = mask_data_for_fit (obj.w_, obj.msk_);
Without the ok, mess returns on L.147, the next 3 lines won't work and have the potential to absorb a previously unset ok and/or an unset mess in the error_message.

2021-05-10 14:35 UTC, abuts approved these changes
good way of learning the code, but from the big picture point of view -- stylistic changes not worth much attention. Does unit test exist for simulation? If not, it would be more useful change.  It certainly missing for all identified issues.

2021-05-10 15:27 UTC, cmarooney-stfc approved these changes
Approving, note one comment previously sent

2021-05-10 16:05 UTC, merged