loadsave code project
pace-neutrons/Herbert pull request #393
Opened 2021-10-18 13:04 UTC by abuts

The purpose of the job is to avoid writing the same serialization code for all Horace/Herbert classes.

The PR is not a complete job but the proposal to be expanded on all instrument classes and custom classes.  Please note how sample IX_aperture class lost 2/3 of its code.
So I am inviting the participants to look at the changes, discuss and use in their development. 

I will also use these methods for converting classes into upcoming `nxsqw` file format.

2021-10-18 16:19 UTC, cmarooney-stfc requested changes
Presuming you will do the rest of the instrument bits (or leave it to me) once this infrastructure is working

2021-10-18 16:19 UTC, cmarooney-stfc commented on _test/test_instrument_classes/test_IX_aperture.m
> +        function test_apperture_array_prev_versions(obj)
aperture 1P just to keep it clean

2021-10-19 10:52 UTC, abuts commented on _test/test_instrument_classes/check_matfile_IO.m
> +% ver_str        -- the name of the version string e.g. ver0 for old
that's Toby's function, extracted from one of the tests, disassembled in pieces. But its probably correct to write better description to its arguments

2021-10-19 10:53 UTC, abuts commented on _test/test_instrument_classes/check_matfile_IO.m
> +%                   them from disk
its save/load here as save/load operators are tested

2021-10-19 10:54 UTC, abuts commented on _test/test_instrument_classes/check_matfile_IO.m
> +    arg_name = inputname(i+3);
that's Matlab intrinsic function

2021-10-19 10:56 UTC, abuts commented on _test/test_instrument_classes/check_matfile_IO.m
> +            save(fullfile(tmp_dir,flname),arg_name);
no, its the specific function, used by these particular tests. You do not want to give it options -- will be too complicated&unnecessary

2021-10-19 11:06 UTC, abuts commented on herbert_core/utilities/classes/@serializable/serializable.m
> +            else % call private implementation
? do not understand this remark. The `else` is calling private function `loadobj_` which does the rest of the processing.  For what it does look at `loadobj_` one does not want to repeat the same description in two independent places.

2021-11-02 21:17 UTC, merged