Use null experiment components
pace-neutrons/Herbert pull request #407
Opened 2022-01-12 09:10 UTC by cmarooney-stfc

IX_inst and IX_samp, being the base classes of IX_inst_DGfermi (and other instruments) and IX_sample, have been deprecated as classes representing absence of instrument or sample data. IX_null_inst and IX_null_sample are used instead. This PR makes the change.

2022-01-12 09:11 UTC, cmarooney-stfc commented
This PR parallels an equivalent one about to be made in Horace. Individual PRs should fail, they have been tested together in a branch build and are OK.

2022-01-12 17:28 UTC, abuts requested changes
partial remarks.

2022-01-12 17:28 UTC, abuts commented on herbert_core/classes/instrument_classes/instrument/@IX_samp/IX_samp.m
> +        %{
If you make class serializable, this method should be removed

2022-01-12 17:28 UTC, abuts commented on herbert_core/classes/instrument_classes/instrument/@IX_samp/IX_samp.m
> +        %{
If you make class serializable, this method should be modified according to template.
                obj = IX_samp();
                obj = loadobj@serializable(S,obj);

as there is empty constructor involved, the class can not be abstract

2022-01-12 17:28 UTC, abuts commented on herbert_core/classes/instrument_classes/instrument/instruments/@IX_inst/IX_inst.m
>          function is = isempty(obj)
as you introduced null_inst, this either should not here or always return false (or array of false, the size of obj -- certainly when heterogeneous is removed) 
You probably better remove this method, as default `isempty` would return `false` so no point of creating duplication. 

null_inst should overload `isempty` to `true`

2022-01-12 17:28 UTC, abuts commented on herbert_core/utilities/classes/@IX_data_1d/IX_data_1d.m.orig
> +    % IX_data_1d class implements main operation with 1-dimensional data
this file should be removed (`.orig`)

2022-01-31 10:35 UTC, cmarooney-stfc commented on herbert_core/utilities/classes/@IX_data_1d/IX_data_1d.m.orig
> +    % IX_data_1d class implements main operation with 1-dimensional data
done

2022-02-02 10:39 UTC, merged